export const FETCH_FILMS = 'FETCH_FILMS';
export const FILMS_ARE_FETCHING = 'FILMS_ARE_FETCHING';
export const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS';
export const FETCH_FILMS_ERROR = 'FETCH_FILMS_ERROR';
export const CHANGE_SEARCH_BY = 'CHANGE_SEARCH_BY';
export const SELECT_FILM = 'SELECT_FILM';
export const SORT_BY_RELEASE = 'SORT_BY_RELEASE';
